# Generated by Django 4.2.3 on 2025-10-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('MacBook', 'MacBook'), ('DELL', 'DELL'), ('Lenovo', 'Lenovo')], max_length=256)),
                ('year', models.SmallIntegerField()),
                ('RAM', models.SmallIntegerField()),
                ('HDD', models.SmallIntegerField()),
                ('price', models.FloatField()),
                ('count_available', models.SmallIntegerField()),
                ('added_date', models.DateField()),
            ],
        ),
    ]
