# Generated by Django 4.2.3 on 2025-10-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('not_published', 'не опубликован'), ('published', 'опубликован'), ('banned', 'забанен')], max_length=20)),
                ('create_date', models.DateField()),
                ('publish_date', models.DateField()),
                ('category', models.CharField(choices=[('computers', 'Компьютеры'), ('coding', 'Кодинг'), ('soft', 'Софт')], max_length=20)),
            ],
        ),
    ]
